- packages/common/api.js
Changed api user urls according to back-end changes
> Changed api user urls

- packages/common/api.js
Change api items url accordring to back-end changes (`/item` -> `/items`)
> [API] Change api items url

- .drone.yml
- packages/components/List/List.js
Fix crushing app when trying to search elements
> [Search] CAES-1024: Fix search crushing

- .drone.yml
- packages/common/api.js
- packages/components/List/List.js
Reverts caesar-team/caesar-web-client#330
Reason: Merged edit with new api url too early.
> Revert "Hotfix/caes 1024 fix searching"

- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordStep.js
> [MastepPass] CAES-666: Added copy notification

- packages/common/package.json
- packages/components/Common/ContentEditable.js
- packages/components/Common/index.js
- packages/components/SecureMessage/SecureMessage.js
- packages/components/SecureMessage/SecureMessageForm.js
- packages/components/SecureMessage/SecureMessageLink.js
- packages/components/SecureMessage/common.js
- packages/components/SecureMessage/constants.js
- packages/components/SecureMessage/styles.js
- packages/components/index.js
- packages/components/package.json
- packages/secure-app/package.json
- yarn.lock
1. Remove focus from the result field.
2. When you click on the result field you copied the text.
3. Add the switch for the passwordless link.
4. Add the expire text.
**Example of the default text:**
```
Please, follow the link and enter the password
- - - - - - - - - - - - - - - - - - - - - - - - - -
URL: http://localhost:3001/message/15c8ea7f-4d3e-41f9-b451-8d4b9150e53a
Password: 4si)pwOE
Expire within: 1 hour
- - - - - - - - - - - - - - - - - - - - - - - - - -
Securely created with http://localhost:3001
```
**Example of the passwordless link:**
```
Please, follow the link and enter the password
- - - - - - - - - - - - - - - - - - - - - - - - - -
URL: http://localhost:3001/message/eyJtZXNzYWdlSWQiOiIxNWM4ZWE3Zi00ZDNlLTQxZjktYjQ1MS04ZDRiOTE1MGU1M2EiLCJwYXNzd29yZCI6IjRzaSlwd09FIn0=
Expire …
```
> Some refactoring for the secure app

- packages/components/Input/Input.js
- packages/components/Layout/LayoutConstructor.js
> [Layout] CAES-953: Fixed background

- packages/common/constants.js
- packages/components/Error/Error.js
- packages/containers/SecureMessage/SecureMessage.js
> [Secure] CAES-1039: Add links to secure

- packages/containers/SecureMessage/SecureMessage.js
> [Secure] CAES-1039: Relocate button

- .dockerignore
- packages/common/utils/passwordGenerator.js
- packages/common/utils/string.js
- packages/components/SecureMessage/common.js
- packages/components/SecureMessage/styles.js
- packages/containers/SecureMessage/steps/MessageStep.js
- packages/secure-app/package.json
- packages/web-app/package.json
- yarn.lock
Use custom escapeHTML instead of encodeURI, use escapeHTML for showing the text data with html tags when we use dangerouslySetInnerHTML.
> [Project] Fix #CAES-1106

- .gitignore
- packages/common/utils/file.js
- packages/common/validation/constants.js
- packages/common/validation/schema.js
- packages/common/validation/utils.js
- packages/components/File/File.js
- packages/components/Uploader/Uploader.js
- packages/secure-app/server.js
- packages/web-app/package.json
- yarn.lock
Bug: Fix wrong size of files,
Refactoring: working with files and filenames
> [Secure Message] Critical: fix the crash with non-latin chars in the name of attachments.

- packages/common/api.js
> [Auth] CAES-1146: Fix route

- packages/common/api.js
> [Items] CAES-1147: User /items routing instead of /item

- packages/common/hooks/useItemTeamAndListOptions.js
- packages/common/utils/team.js
- packages/components/CreateForm/components/FormHeader.js
- packages/components/Item/components/ItemHeader.js
- packages/components/MenuList/MenuList.js
- packages/components/MoveModal/MoveModal.js
- packages/components/ShareModal/components/Team.js
- packages/components/TeamCard/TeamCard.js
- packages/components/TeamsList/TeamsList.js
- packages/containers/Team/Team.js
> [Teams] CAES-1059: Update domain team

- packages/common/sagas/entities/item.js
- packages/common/sagas/workflow.js
> [Items] CAES-1070: Fix new item reset from view

- packages/common/selectors/user.js
> [Items] CAES-1115: Fix selector

- packages/common/actions/user.js
- packages/common/reducers/user.js
- packages/common/sagas/entities/item.js
- packages/common/sagas/entities/team.js
- packages/common/sagas/workflow.js
- packages/common/selectors/entities/team.js
- packages/common/selectors/user.js
- packages/common/utils/item.js
> [Items] CAES-1193: Add autogeneration of team system item

- packages/common/actions/entities/team.js
- packages/common/reducers/entities/team.js
- packages/common/sagas/entities/member.js
- packages/common/sagas/entities/team.js
> [Teams] CAES-1199: Fix users list after creation

- packages/components/TeamsList/TeamsList.js
> [Teams] CAES-1120: Fix personal duplicate

- packages/common/sagas/entities/item.js
> [System] CAES-1220: Add separated saga for save items

- packages/common/utils/authUtils.js
- packages/containers/SignIn/SignIn.js
- packages/containers/SignIn/SignInForm.js
> [SignIn] CAES-1002: Fix errors display

- packages/common/validation/constants.js
- packages/components/MenuList/components/ListInput.js
- packages/components/MenuList/components/ListItem.js
- packages/components/MenuList/components/MenuListInner.js
> [List] CAES-607: Update error display

- packages/common/api.js
- packages/common/constants.js
- packages/common/sagas/user.js
- packages/common/utils/token.js
- packages/containers/SignIn/SignIn.js
Add request /api/logout to delete fingerprint from data base.
Add x-fingerprint in each request if exist in local storage.
> [TrustedDevice] CAES-1202: Change the flow of trustedDevice token

- packages/common/validation/constants.js
- packages/containers/SignIn/SignIn.js
> [SignIn] CAES-1002: Update error message

- packages/common/normalizers/schemas/item.js
- packages/common/normalizers/schemas/list.js
- packages/components/AddItem/AddItem.js
- packages/components/Item/components/ItemHeader.js
- packages/components/MenuList/components/ListItem.js
- packages/components/MenuList/components/MenuListInner.js
- packages/components/TeamCard/TeamCard.js
- packages/containers/Team/createColumns.js
- packages/containers/TeamList/TeamList.js
> Go to the permissions from the normalizr

- packages/components/Layout/DashboardLayout.js
> [Items] CAES-1348: Add check for keypair to show button

- packages/components/AddItem/AddItem.js
- packages/components/Item/Item.js
- packages/components/Item/components/ItemHeader.js
- packages/components/MenuList/components/ListItem.js
- packages/components/MenuList/components/MenuListInner.js
- packages/components/TeamCard/TeamCard.js
- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordCreateForm.js
- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordStep.js
Also fix runtime undefined errors
> [SignUp] CAES-1368: Change flow when copy master password

- packages/common/sagas/entities/team.js
> Request admins before adding to a team

- packages/web-app/next.config.js
- packages/web-app/server.js
> Fix the service-worker.js is not found

- packages/containers/Team/Team.js
> [Teams] CAES-1372: Fix team operations

- packages/common/sagas/entities/team.js
- packages/containers/Team/Team.js
> Fix adding a new member to a team

- packages/common/sagas/entities/item.js
> Send the title to the server

- packages/common/reducers/entities/team.js
> [Teams] CAES-1370: Fix edit team

- packages/containers/TeamList/TeamList.js
> [Teams] CAES-1278: Update counter for pinned teams

- packages/common/sagas/workflow.js
> Fix sagas order

- packages/common/sagas/workflow.js
> Fix getting the team lists

- packages/common/normalizers/schemas/member.js
> [Teams] CAES-1410: Fix member after invitation

- packages/common/utils/error.js
- packages/common/utils/item.js
> [Teams] CAES-1371: Fix error display

- packages/common/api.js
- packages/common/constants.js
- packages/common/normalizers/normalizers.js
- packages/common/normalizers/schemas/index.js
- packages/common/normalizers/schemas/member.js
- packages/common/normalizers/schemas/user.js
- packages/common/reducers/entities/member.js
- packages/common/reducers/entities/team.js
- packages/common/sagas/common/anonymous.js
- packages/common/sagas/common/share.js
- packages/common/sagas/entities/member.js
- packages/common/sagas/entities/team.js
- packages/common/sagas/workflow.js
- packages/common/selectors/entities/member.js
- packages/common/selectors/entities/team.js
- packages/common/selectors/user.js
- packages/common/selectors/workflow.js
- packages/containers/Team/Team.js
- packages/containers/Team/constants.js
- packages/containers/Team/createColumns.js
- packages/web-app/pages/settings/team/[id]/index.js
Now we have the new one normaliz and the new member scheme, you should use this for a member entity.
> Rename the roles

- packages/containers/Bootstrap/Bootstrap.js
> [Bootstrap] CAES-1160: Add check for anonymous roles

- packages/components/SettingsWrapper/SettingsWrapper.js
- packages/containers/Import/Import.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/Steps/DataStep/styles.js
> [Import] CAES-1436: Update layout

- packages/containers/SecureMessage/SecureMessage.js
- packages/containers/SecureMessage/styles.js
> [Secure] CAES-1430: Update layout

- packages/common/sagas/entities/item.js
> [Import] CAES-1441: Add titles to request

- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordCreateForm.js
> [SignUp] CAES-1421: Fix button label

- packages/containers/SecureMessage/styles.js
> [Secure] CAES-1430: Fix height on mobile

- packages/containers/Team/createColumns.js
> [Teams] CAES-1412: Fix prop error

- packages/components/List/Item/index.js
> [Items] CAES-1461: Fix shared users display

- packages/common/sagas/workflow.js
> Show the dash if the vault is empty

- packages/components/Modal/Portal.js
- packages/components/MoveModal/MoveModal.js
- packages/components/ShareModal/ShareModal.js
> [Modal] CAES-1146: Add scroll to modal

- packages/common/actions/entities/list.js
- packages/common/reducers/entities/list.js
- packages/common/reducers/entities/team.js
- packages/common/root/persist.js
- packages/common/sagas/application.js
- packages/common/sagas/common/anonymous.js
- packages/common/sagas/entities/item.js
- packages/common/sagas/entities/list.js
- packages/common/sagas/entities/team.js
- packages/common/sagas/workflow.js
- packages/common/selectors/counts.js
- packages/common/selectors/currentUser.js
- packages/common/selectors/entities/item.js
- packages/common/selectors/entities/list.js
- packages/common/selectors/entities/team.js
- packages/common/selectors/workflow.js
- packages/common/utils/item.js
- packages/common/utils/loginUtils.js
- packages/components/MenuList/components/ListItem.js
- packages/components/MenuList/components/MenuListInner.js
- packages/containers/Dashboard/components/MiddleColumn.js
- packages/containers/Dashboard/components/ShareModal.js
> Remove the children workflow, now we use the listId in items

- packages/common/actions/entities/list.js
- packages/common/reducers/entities/list.js
- packages/common/root/persist.js
- packages/common/sagas/application.js
- packages/common/sagas/common/anonymous.js
- packages/common/sagas/entities/item.js
- packages/common/sagas/entities/list.js
- packages/common/sagas/entities/team.js
- packages/common/sagas/workflow.js
- packages/common/selectors/counts.js
- packages/common/selectors/currentUser.js
- packages/common/selectors/entities/item.js
- packages/common/selectors/entities/list.js
- packages/common/selectors/entities/team.js
- packages/common/selectors/workflow.js
- packages/common/utils/item.js
- packages/common/utils/loginUtils.js
- packages/components/MenuList/components/ListItem.js
- packages/components/MenuList/components/MenuListInner.js
- packages/containers/Dashboard/components/MiddleColumn.js
- packages/containers/Dashboard/components/ShareModal.js
* Show items based on the listId fields
* WIP
* Wipe out the children workflow
* Clean the code
* Rename the method
* Fix LGTM
> Remove the children workflow, now we use the listId in items (#601)

- packages/common/sagas/workflow.js
- packages/common/utils/item.js
- packages/components/List/FixedSizeItem.js
- packages/components/List/Item/index.js
- packages/containers/Dashboard/components/MiddleColumn.js
> Fix recursive loop, Fix on-demand item error.

- packages/common/reducers/workflow.js
- packages/common/sagas/common/decryption.js
- packages/common/sagas/workflow.js
- packages/common/utils/item.js
- packages/components/Item/ItemByType.js
- packages/components/List/Item/index.js
> Fix the bug, fix the double on-demand

- packages/common/sagas/entities/member.js
- packages/components/MemberList/components/RoleSelector.js
> [Team]: Fix field name

- packages/containers/TeamList/TeamList.js
- packages/containers/TeamList/index.js
> [Teams] CAES-1516: Add tabs for manager

- packages/common/sagas/entities/team.js
> Fix actions of create a team or add a member

- packages/containers/Dashboard/components/MiddleColumn.js
- packages/containers/Dashboard/utils.js
> Fix search

- packages/components/List/Item/index.js
> Fix showing a fav icon

- packages/components/Select/Select.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/Steps/DataStep/styles.js
> [Import] CAES-1510: Fix list dropdown

- packages/containers/Import/Steps/ImportingStep/ImportingStep.js
> [Import] CAES-1466: Remove decimals

- packages/components/MoveModal/MoveModal.js
- packages/components/ShareModal/ShareModal.js
> [Popups] CAES-1534: Fix buttons position

- packages/common/constants.js
- packages/containers/Team/Team.js
- packages/containers/Team/constants.js
- packages/containers/Team/createColumns.js
> [Teams] CAES-1393: Remove guest role for new member

- packages/components/DottedMenu/DottedMenu.js
- packages/components/TeamCard/TeamCard.js
- packages/containers/Team/constants.js
- packages/containers/TeamList/TeamList.js
> [Teams] CAES-1538: Fix menu close

- packages/components/ShareModal/ShareModal.js
> [Share] CAES-1572: Disable share for teams

- packages/containers/TeamList/TeamList.js
> [Teams] CAES-1516: Fix manager tab

- packages/common/utils/item.js
> [Teams] CAES-1564: Fix titles with symbols

- packages/containers/TeamList/TeamList.js
> [Teams] CAES-1522: Fix edit

- packages/common/utils/url.js
- packages/components/CreateForm/types/Credentials.js
> [Items] CAES-1538: Fix default favicons

- packages/components/TeamModal/TeamModal.js
- packages/components/TeamModal/schema.js
- packages/containers/TeamList/TeamList.js
> [Teams] CAES-1570: Add team title validation

- packages/components/Item/MultiItem.js
- packages/components/Item/components/ItemHeader.js
- packages/components/Item/components/OwnerAndShares.js
- packages/containers/Team/Team.js
> [Icons] CAES-1559: Add tooltips

- packages/components/ItemFields/view/Input.js
- packages/components/ItemFields/view/Website.js
> [Items] CAES-1611: Fix website field validation

- packages/common/validation/constants.js
- packages/components/TeamModal/TeamModal.js
- packages/components/TeamModal/schema.js
> [Teams] CAES-1570 & CAES-1619: Fix team title validation

- packages/common/validation/constants.js
- packages/components/TeamModal/TeamModal.js
> [Teams] CAES-1570: Update schema

- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordConfirmForm.js
> [MasterPass] CAES-1600: Fix validation for confirm

- packages/containers/Team/Team.js
- packages/containers/Team/createColumns.js
> [Team] CAES-1576: Fix admin buttons

- packages/containers/Dashboard/components/MiddleColumn.js
> [Items] CAES-1635: Fix bulk actions

- packages/containers/Dashboard/components/MiddleColumn.js
> [Items] CAES-1635: Fix permissions

- packages/common/api.js
- packages/common/package.json
- packages/components/SecureMessage/page.js
- packages/web-app/package.json
- yarn.lock
> Add DEBUG for axios

- packages/components/SettingsWrapper/SettingsWrapper.js
- packages/components/TeamCard/TeamCard.js
- packages/components/VaultList/VaultList.js
> [Teams] CAES-1574: Fix long team titles

- packages/common/constants.js
- packages/containers/Import/Import.js
- packages/containers/Import/Steps/ImportingStep/ImportingStep.js
> [Import] CAES-1613: Reset state for new import

- packages/components/Select/Select.js
- packages/components/Select/styles.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/Steps/DataStep/styles.js
> [Import] CAES-1510: Fix long titles

- packages/components/Select/styles.js
> [Import] CAES-1510: Fix title wrap

- packages/containers/Import/Import.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/index.js
> [Import] CAES-1219: Add ability to import to team

- packages/containers/Import/Import.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/index.js
> [Import] CAES-1219: Fix decryption and list selection

- packages/containers/Import/Import.js
- packages/containers/Import/Steps/DataStep/DataStep.js
- packages/containers/Import/index.js
> [Import] CAES-1695: Fix current list selection

- packages/components/MenuList/MenuList.js
- packages/components/VaultList/VaultList.js
> [Items] CAES-1656: Reset search while changing team

- packages/components/ItemFields/view/Note.js
> [Items] CAES-1706: Fix note edit

- packages/common/sagas/workflow.js
- Add trycatch when can not download file (prevent a broken page).
- When default list is deleted, there is the error in console 'id of undefined'.
> CAES-1692: Fix login flow console error

- packages/common/sagas/workflow.js
- packages/components/MenuList/components/DummyLists.js
- packages/components/VaultList/VaultList.js
> [Items] CAES-1656: Fix reset

- packages/common/actions/entities/item.js
- packages/common/reducers/entities/item.js
- packages/common/sagas/common/share.js
> [Share] CAES-1700: Updated lastUpdate after access revoke

- packages/containers/Bootstrap/constants.js
> [SignUp] CAES-1727: Fix password validation

- packages/components/AuthTitle/AuthTitle.js
- packages/components/Button/Button.js
- packages/components/Layout/BootstrapHeader.js
- packages/components/Layout/LayoutConstructor.js
- packages/components/Layout/SecondaryHeader.js
- packages/components/NavigationPanel/NavigationPanel.js
- packages/containers/SignUp/SignUpForm.js
> [Layout] CAES-1668: Added adaptive for sign and auth pages

- packages/common/constants.js
- packages/common/sagas/entities/item.js
- packages/containers/Dashboard/components/ConfirmMoveToTrashModal.js
> [Items] CAES-1724: Update notifications

- packages/components/Layout/SecondaryHeader.js
> [Layout] CAES-1668: Fix header

- packages/components/AuthDescription/AuthDescription.js
- packages/components/AuthTitle/AuthTitle.js
- packages/components/Layout/AuthLayout.js
- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordConfirmForm.js
- packages/containers/Bootstrap/Steps/MasterPasswordStep/MasterPasswordCreateForm.js
- packages/containers/Bootstrap/Steps/TwoFactorStep/TwoFactorForm.js
- packages/containers/SignIn/SignInForm.js
- packages/containers/SignUp/SignUpForm.js
> [Layout] CAES-1668: Update adaptive styles

- packages/containers/SignIn/SignInForm.js
- packages/containers/SignUp/SignUpForm.js
> [Layout] CAES-1668: Fix button uppercase

- packages/common/sagas/common/move.js
> [Items] CAES-1724: Update notification for moving

- packages/components/Item/Item.js
> [Items] CAES-1724: Update restore notification

- packages/components/Input/StrengthIndicator.js
- packages/components/TooltipPasswordGenerator/TooltipPasswordGenerator.js
- packages/containers/Bootstrap/Steps/TwoFactorStep/TwoFactorBackupForm.js
- packages/containers/SignUp/SignUpForm.js
> [SignUp] CAES-1668: Update styles
